name: Sync NeoDB Data and rss_subscription
on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  NeoDB:
    name: Sync NeoDB Data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 检查是否安装了 JQ
    - name: Check JQ
      run: |
        if ! command -v jq &> /dev/null; then
          echo "jq is not installed. Installing..."
          sudo apt-get update
          sudo apt-get install -y jq
        else
          echo "jq is already installed."
        fi
        # 把当前目录保存到环境变量中
        echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

    # 获取本地现有文件的标记数
    # - name: Get Current Count
    #   run: |
    #     CURRENT_COUNT() {
    #       jq '.count' data/neodb/book_progress.json
    #     }
    #     echo "CURRENT_COUNT=$(CURRENT_COUNT)" >> $GITHUB_ENV

    - name: Get NeoDB JSON
      run: |
        curl -X 'GET' \
        'https://neodb.social/api/me/shelf/progress?category=book' \
        -H 'accept: application/json' \
        -H 'Authorization: Bearer ${{ secrets.NEODB_ACCESS_TOKEN }}' > book_progress.json

         # 更新 NeoDB 数据
        cp -f book_progress.json ${{ env.WORK_DIR }}/data/neodb/

    - name: Get rss_subscription
      run: |
        curl https://raw.githubusercontent.com/EuDs63/TinyTinyRSS-OPML-to-MD-Table/main/rss_subscription.json > rss_subscription.json

        # 更新rss_subscription数据
        cp -f rss_subscription.json ${{ env.WORK_DIR }}/data/rss/

    # 把修改后的数据提交到 GitHub 仓库
    - name: Git Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'update neodb data'
        add: './data'

    # 调用另外的 GitHub Actions 构建 Hugo
    - name: Build Hugo and Deploy
      uses: peter-evans/repository-dispatch@v2
      with:
          event-type: "Deploy Hugo site to Pages"

